### ISSUE TITLE
Puzzler!

### ISSUE THREAD

**Issue by andyl** [GrzegorzKozub/vim-elixirls#2]
vim-elixirls has been working beautifully until today, when I upgraded all my plugins.

Now I get linting in both vim and neovim when I edit `mix.exs`, but **no other file**.  Linting does not work if I rename `mix.exs` to `mixx.exs` or `mix.ex`.

I watch for the elixir-ls process (using `watch pgrep -f elixir -a`) and see no difference between the working and failing cases. 

Puzzling!  Have any clues as to what may be happening here, or how to diagnose?

**Comment by GrzegorzKozub** [comment]
This vim-elixirls plugin is just a wrapper for ElixirLS. It clones that
repo and compiles it.

I've seen ElixirLS has been recently updated, so you may try checking out
an earlier version in elixir-ls folder and then running ElixirLsCompile.

Also, ElixirLS requires your code be compiled with the same version of
Elixir that ElixirLS itself.

**Comment by andyl** [comment]
Thanks for the note - I see that VsCode has the same strange behavior so I suspect the problem is with ElixirLS.  Learning about Elixir Logging and Tracing - will post here if/when I figure it out.

**Comment by andyl** [comment]
Well it's working now - there was some sort of conflict between asdf, code versions, and so forth.
